# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiApp_app', '0003_auto_20170223_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='users',
            field=models.ManyToManyField(related_name='all_courses', to='loginRegistration_app.User'),
        ),
    ]
